### ISSUE TITLE
Imma use this

### ISSUE THREAD

**Issue by b12f** [ChaosMarc/letsencrypt-nginx-proxy-companion-armhf#1]
Yo after a lot of searching I stumbled across this armhf version of le-companion. Seems to me like this is a personal project of yours so far, but since it also seems you've been active in keeping it updated. Hit me up if you need help or smth, I'd prefer not ending up with an unmaintained version.

**Comment by b12f** [comment]
Thanks for the work and all ;) feel free to close this issue

**Comment by ChaosMarc** [comment]
I'm happy that my armhf version helps you :)
There is no maintenance effort for my part as it is automated completely on my armhf based [odroid](https://www.hardkernel.com/main/products/prdt_info.php?g_code=G143452239825) which runs 24/7. I have a cronjob that runs the update.sh which itself checks out the latest changes from JrCs repository, builds and pushes it to dockerhub. Since a few commits there is no need anymore for changes (automated with sed replacement) to the Dockerfile itself, just building it suffices.
